name: Docker Image CI Wildlens_Prediction

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: wildlens_prediction_environment
    env:
      DOCKER_REGISTRY_HOST: ${{ vars.DOCKER_REGISTRY_HOST }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      FINAL_IMAGE_NAME: ${{ vars.DOCKER_REGISTRY_HOST }}/${{ vars.IMAGE_NAME }}:latest
    steps:
    # Build the docker image
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.FINAL_IMAGE_NAME }}


    # Login to the registry
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ env.DOCKER_REGISTRY_HOST }}
        # Username used to log against the Docker registry
        username: ${{ env.DOCKER_REGISTRY_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ env.DOCKER_REGISTRY_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: false
        # Log out from the Docker registry at the end of a job
        logout: true

    # Push image to the registry
    - name: Docker push
      run: docker push ${{ env.FINAL_IMAGE_NAME }}
    
          
